# permissions for end users to view hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - hellos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - hellos/status
  verbs:
  - get
